const data = Job.insertMany([{
  salary: "120000",
  skills: ["CSS, JS, Python"],
  benefits: "Health, stocks, WiFi, free snacks & beverages",
  totalPositions: 10,
  joiningDate: "2023/12/15",
  responsibilities: [
    "Develop and maintain web applications",
    "Collaborate with cross-functional teams",
    "Troubleshoot and debug issues",
  ],
  companyId: "65d5eb85f142aec9b20c2785", 
  experience: "2-4 years",
  vacancies: 3,
  postedDate: "2023/11/25",
  companyName: "TechCo",
  position: "Software Engineer",
  jobDesc:
    "We are seeking a talented Software Engineer to join our dynamic team...",
},
{
  responsibilities: [
    "Implement responsive designs",
    "Collaborate with UX designers",
    "Optimize web applications for performance",
  ],
  joiningDate: "2023/12/10",
  skills: ["HTML", "CSS", "JavaScript"],
  jobDesc:
    "Join our dynamic team of developers and contribute to building user-friendly interfaces...",
  vacancies: 4,
  location: "Austin, TX",
  position: "Frontend Developer",
  experience: "2-4 years",
  totalPositions: 8,
  benefits: "Health, stocks, WiFi, free snacks & beverages",
  salary: "100000",
  companyName: "TechCo",
  companyId: "65d5eb85f142aec9b20c2785", 
  postedDate: "2023/11/25",
},
{
  vacancies: "3",
  companyId: "65d5eb85f142aec9b20c2785", 
  position: "Data Analyst",
  companyName: "TechCo",
  joiningDate: "2024-02-09",
  skills: ["Python", "R", "PyTorch"],
  benefits: "Paid Leaves",
  postedDate: "04/01/2024, 14:51:52",
  jobDesc: "Should be interested in leaning and making real word solutions",
  salary: "10000",
  responsibilities: ["Should be working 2 days a week"],
  totalPositions: "3",
  experience: "2 Yr",
},
{
  benefits: "Health, stocks, WiFi, free snacks & beverages",
  vacancies: 5,
  location: "Seattle, WA",
  responsibilities: [
    "Develop predictive models",
    "Conduct statistical analysis",
    "Collaborate with cross-functional teams",
  ],
  totalPositions: 12,
  experience: "4-6 years",
  jobDesc:
    "We are looking for a skilled Data Scientist to analyze and interpret complex data sets...",
  companyName: "DataTech",
  skills: ["Python", "R", "Machine Learning"],
  joiningDate: "2023/12/15",
  salary: "530000",
  postedDate: "2023/11/28",
  position: "Data Scientist",
  companyId: "65d5eb85f142aec9b20c2785",
},
{
  position: "Data Analyst",
  companyName: "DataInsights",
  companyId: "65d5eb85f142aec9b20c2785",
  joiningDate: "2023-12-18",
  postedDate: "2023-11-25",
  skills: ["SQL", "Python", "Data Visualization"],
  jobDesc:
    "Join our data analysis team to derive insights and make data-driven decisions...",
  experience: "2-4 years",
  responsibilities: [
    "Analyze large datasets",
    "Create data visualizations",
    "Collaborate with cross-functional teams",
  ],
  totalPositions: 6,
  vacancies: 2,
  benefits: "Health, stocks, remote work options, training programs",
  salary: "1000000",
  location: "New York, NY",
},
{
  companyName: "TechCo",
  responsibilities: [
    "Develop and maintain both frontend and backend components,\nCollaborate with UI/UX designers,\nTroubleshoot and debug issues",
  ],
  benefits: "Health , Paid leaves",
  joiningDate: "2024-11-16",
  experience: "5 years",
  companyId: "65d5eb85f142aec9b20c2785", postedDate: "1/4/2024, 10:47:15 PM",
  vacancies: 2,
  totalPositions: "4",
  salary: "10000000",
  position: "ML Engineer",
  skills: ["C++", "C", "C#"],
  jobDesc:
    "Develop and maintain both frontend and backend components\nCollaborate with UI/UX designers\nTroubleshoot and debug issues",
},
{
  totalPositions: 8,
  position: "Full Stack Developer",
  salary: "600000",
  jobDesc:
    "We're seeking a talented Full Stack Developer to contribute to the development of innovative web applications...",
  joiningDate: "2023-12-20",
  experience: "3-5 years",
  responsibilities: [
    "Develop and maintain both frontend and backend components",
    "Collaborate with UI/UX designers",
    "Troubleshoot and debug issues",
  ],
  vacancies: 4,
  companyName: "CodeCrafters",
  companyId: "65d5eb85f142aec9b20c2785",
  benefits: "Health, stocks, flexible work hours, gym membership",
  skills: ["JavaScript", "Node.js", "React", "MongoDB"],
  location: "Austin, TX",
  postedDate: "2023-11-30",
},
{
  vacancies: 2,
  companyName: "DesignHub",
  experience: "3-5 years",
  joiningDate: "2023/12/15",
  position: "UX Designer",
  totalPositions: 8,
  location: "New York, NY",
  jobDesc:
    "Join our design team and contribute to creating stunning user experiences...",
  postedDate: "2023/11/25",
  salary: "100000",
  companyId: "65d5eb85f142aec9b20c2785",
  responsibilities: [
    "Create wireframes and prototypes",
    "Collaborate with product managers and developers",
    "Conduct user research",
  ],
  skills: ["UI/UX design", "Adobe Creative Suite"],
  benefits: "Health, stocks, WiFi, free snacks & beverages",
},
{
  jobDesc: "Should be having matching skill set",
  joiningDate: "2024-10-23",
  salary: "10000",
  postedDate: "2/19/2024, 6:39:33 PM",
  position: "Junior  SDE",
  experience: "0-5 years",
  benefits: "None",
  totalPositions: "12",
  vacancies: "12",
  skills: "Python, NodeJS, UI/UX",
  responsibilities: ["should be available for next 2 month in offline"],
  companyId: "65d5eb85f142aec9b20c2785",
  companyName: "TechCo",
},]);
