export const jobseeker = [
  {
    yoc: "2025",
    img: "https://firebasestorage.googleapis.com/v0/b/inspiringgoo.appspot.com/o/users%2FFmsCJW4R0PYH0trCnX7lWkv1GAV2?alt=media&token=38d64b4f-40e5-4758-9da4-82df1fa2fbda",
    fname: "Sonish",
    mobile: "7842266539",
    marital: "single",
    nationality: "India",
    address: "bh1 127 sricity",
    fav: [],
    email: "sonish.k21@iiits.in",
    password: "qwe123",
    skills: ["c", "c++", "java"],
    yoa: "2021",
    i_name: "IIIIT SriCity",
    dob: "2003-09-16",
    qualification: "bachelors",
    gender: "Male",
  },
  {
    i_name: "GRIET",
    yoc: "2025",
    skills: ["c", "c++", "java"],
    qualification: "bachelors",
    address: "Flat.No 402 ,Yogitha Arcade ,Balaji Nagar ,Kukatpally",
    dob: "2004-05-22",
    password: "qwe123",
    email: "jayenthg@gmail.com",
    marital: "single",
    gender: "Male",
    fav: [],
    fname: "Abhinav Gumpu",
    yoa: "2021",
    nationality: "India",
    mobile: "7702003227",
  },
  {
    dob: "2004-10-22",
    mobile: "7569871641",
    img: "https://firebasestorage.googleapis.com/v0/b/inspiringgoo.appspot.com/o/users%2FOY28fA2q4EYNgd9Ykqu3s2o4njR2?alt=media&token=2c70a3d4-c7e1-4f3d-9442-c6c627d73442",
    yoc: "2025",
    i_name: "Indian Institute of Information Technology Sricity",
    marital: "single",
    email: "susrithasabbini@gmail.com",
    password: "qwe123",
    yoa: "2021",
    gender: "Female",
    skills: ["c", "c++", "java"],
    address: "H.No: 5-1-103/A/44, MRF Colony, Ganesh Nagar",
    fav: [],
    nationality: "India",
    fname: "Sabbini Susritha",
    qualification: "bachelors",
  },
  {
    email: "rahulreddy.b21@iiits.in",
    yoc: "2025",
    fname: "Rahul Reddy",
    password: "qwe123",
    qualification: "bachelors",
    fav: [],
    nationality: "India",
    i_name: "IIIT SriCity",
    yoa: "2021",
    marital: "single",
    img: "https://firebasestorage.googleapis.com/v0/b/inspiringgoo.appspot.com/o/users%2FIijKNGPC0aUJIZiIQ3ehjkgFcXo2?alt=media&token=fb14fb58-420b-41b2-a8cd-d5eee3db72b2",
    mobile: "8332003444",
    skills: ["c", "c++", "java"],
    gender: "Male",
    address: "XYZ",
    dob: "2003-10-28",
  },
  {
    yoc: "2025",
    marital: "single",
    skills: ["c", "c++", "java"],
    gender: "Male",
    address: "IIIT Sri City",
    fav: [],
    mobile: "9063830998",
    fname: "Beera Sravan Krishna",
    yoa: "2021",
    email: "sravan.b21@iiits.in",
    password: "qwe123",
    nationality: "India",
    i_name: "IIIT Sri City",
    dob: "2002-07-02",
    qualification: "bachelors",
  },
  {
    skills: ["c", "c++", "java"],
    mobile: "5386869736",
    dob: "1999-05-11",
    fname: "maher juma",
    i_name: "maher",
    fav: [],
    yoa: "2015",
    nationality: "Bahamas (the)",
    marital: "married",
    password: "qwe123",
    yoc: "2020",
    email: "maher@gmail.com",
    address: "denizciler",
    qualification: "doctoral",
    gender: "Male",
  },
  {
    nationality: "India",
    fav: [],
    i_name: "Indian Instititute of Information technology Sri City ",
    qualification: "bachelors",
    fname: "Pavan Kumar Padarthy",
    yoc: "2025",
    img: "https://firebasestorage.googleapis.com/v0/b/inspiringgoo.appspot.com/o/users%2FIqYjgGMFzeTnceIAVQbxOrRNWsU2?alt=media&token=cdf16bf0-c02d-4425-b4a1-4f1b0bb9ff35",
    marital: "single",
    skills: ["c", "c++", "java"],
    gender: "Male",
    yoa: "2021",
    dob: "2003-11-16",
    mobile: "7337326976",
    password: "qwe123",
    address:
      "IIIT Sricity Academic block,gnan marg,satyvedu mandal ,Andhrapradesh,517646",
    email: "jppavan2003@gmail.com",
  },
  {
    yoa: "2021",
    dob: "2003-10-30",
    mobile: "9029967126",
    password: "qwe123",
    email: "mbssnandan08@gmail.com",
    nationality: "India",
    fav: [],
    skills: ["c", "c++", "java"],
    yoc: "2025",
    marital: "single",
    address: "Hydernagar",
    i_name: "CBIT",
    fname: "Nandan",
    qualification: "masters",
    gender: "Male",
  },
  {
    address: "bh1 315",
    marital: "single",
    yoa: "2021",
    dob: "2004-06-23",
    email: "chandrakiran179@gmail.com",
    password: "qwe123",
    gender: "Male",
    skills: ["c", "c++", "java"],
    i_name: "IIIT Sricity",
    fav: [],
    fname: "Chandra kiran",
    qualification: "bachelors",
    yoc: "2025",
    nationality: "India",

    mobile: "9608795086",
  },
  {
    skills: ["c", "c++", "java"],
    password: "qwe123",
    gender: "Male",
    email: "khadar@gmail.com",
    fname: "khadar oothuru",
    fav: [],
    marital: "single",
    yoc: "2025",
    mobile: "9515518830",
    qualification: "graduate",
    i_name: "Indian institute of information technology ",
    img: "https://firebasestorage.googleapis.com/v0/b/inspiringgoo.appspot.com/o/users%2F9cVKuNtuB8c9zVW5jQUTP44nvwo1?alt=media&token=79ec41d9-31ed-400a-ac3d-24183c4ef566",
    nationality: "India",
    dob: "2002-06-22",
    address: "Atmakur",
    yoa: "2021",
  },
  {
    fav: [],
    skills: ["c", "c++", "java"],
    email: "vikrant@gmail.com",
    password: "qwe123",
    address: "IIIT SriCity",
    yoa: "2011",
    mobile: "6237462837",
    fname: "Vikrant",
    yoc: "2015",
    qualification: "masters",
    dob: "1991-12-08",
    marital: "single",
    i_name: "SSS",
    nationality: "India",
    gender: "Male",
  },
];
